import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Toaster } from 'react-hot-toast'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'
import { Tweet } from '../typings'
import { fetchTweets } from '../utils/fetchTweets'

interface Props {
  tweets: Tweet[],
}

export default function Home({ tweets }: Props) {
  // console.log(tweets);
  return (
    <div className='mx-auto lg:max-w-6xl max-h-screen overflow-hidden'>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />

      <main className='grid grid-cols-9 '>
        <Sidebar />
        <Feed tweets={tweets} />
        <Widgets />

        {/* widgets */}
      </main>
      

      

   
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tweets = await fetchTweets();
    
  
  return {
    props: {
      tweets,
    },
  }
}